version: "3.8"
services:
  
  online-shop:
    image: test-image
    container_name: test-container
    restart: always
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8083:3000"







